default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fantastic_journey_api_development

test:
  <<: *default
  database: fantastic_journey_api_test

production:
  <<: *default
  database: fantastic_journey_api
  username: postgres
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>
